version: '3'
services:
  mongodb:
    image: mongo:latest
    volumes:
      - todo-volume2:/data/db
    environment:
       MONGO_INITDB_ROOT_USERNAME: admin
       MONGO_INITDB_ROOT_PASSWORD: admin
    networks:
      - todo_network
    hostname: mongohost
  todoapp:
    build: .
    depends_on:
      - mongodb
    ports:
      - "3000:3000"
    networks:
      - todo_network
networks:
  todo_network:
volumes:
  todo-volume2: