name: PROD Server Pipeline

on:
  workflow_dispatch:
    # inputs:
    #   version:
    #     description: 'Enter the version number (e.g., 1.0.1)'
    #     required: true
    #     default: '0.0.1' # Default value if user does not input

jobs:
  build_and_push:
    runs-on: ubuntu-22.04
    permissions:
      contents: write

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0 # Ensure all tags are fetched

    # Step to create a new tag based on the existing tag
    - name: Create new tag from existing tag
      id: bump
      run: |
        # Get the existing tag from the GitHub context
        EXISTING_TAG=${GITHUB_REF#refs/tags/}
        echo "Existing tag: $EXISTING_TAG/uta\//"

        # Create new tag with 'prod/' prefix
        NEW_TAG="prod/$EXISTING_TAG"
        echo "New tag: $NEW_TAG"

        # Create new tag and push using PAT for authentication
        git tag $NEW_TAG
        git push origin $NEW_TAG
      env:
        GITHUB_TOKEN: ${{ secrets.GIT_TOKEN }}