name: Deploy to AWS ECR and Kubernetes

on:
  push:
    branches:
      - main 
      

permissions:
  contents: read  # For checking out the repository
  
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: Build, tag, and push image to ECR
      env:
        ECR_REGISTRY: 910253526187.dkr.ecr.us-east-1.amazonaws.com
        ECR_REPOSITORY: web-app
        IMAGE_TAG: dev
      run: |
        docker build -t $ECR_REPOSITORY:$IMAGE_TAG .
        docker tag $ECR_REPOSITORY:$IMAGE_TAG $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
        docker rmi $ECR_REPOSITORY:$IMAGE_TAG
        docker rmi $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG

    # - name: Update kubeconfig and restart deployment
    #   run: |
    #     aws eks update-kubeconfig --region eu-west-1 --name Cluster-Production
    #     kubectl rollout restart deployment -n production gymfans-admin-deployment
