name: Create New Tag and Push Docker Image

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Enter the version number (e.g., 1.0.1)'
        required: true
        default: '0.0.1' # Default value if user does not input

jobs:
  build_and_push:
    runs-on: ubuntu-22.04
    permissions:
      contents: write

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0 # Ensure all tags are fetched

    # Step to create a new tag based on the input version
    - name: Create new tag
      id: bump
      run: |
        # Get the version input
        VERSION=${{ github.event.inputs.version }}
        NEW_TAG="uta/$VERSION"
        echo "New tag: $NEW_TAG"

        # Create new tag and push using PAT for authentication
        git tag $NEW_TAG
        git push origin $NEW_TAG
      env:
        GITHUB_TOKEN: ${{ secrets.GIT_TOKEN }}