name: Create New Tag and Push Docker Image

on:
  workflow_dispatch: # Allows manual triggering via GitHub Actions UI

jobs:
  build_and_push:
    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0 # Ensure all tags are fetched
      env:
        GITHUB_TOKEN: ${{ secrets.GIT_TOKEN }}

     # Step to get the latest tag and create a new tag
    - name: Get latest tag and create new tag
      id: bump
      run: |
       # Fetch all tags
       git fetch --tags

       # Get the latest version tag (adjust the pattern if necessary)
       LATEST_TAG=$(git tag --list 'v*' | sort -V | tail -n 1)
       echo "Latest tag: $LATEST_TAG"

       # Increment version (based on your versioning strategy)
       BASE_VERSION=$(echo $LATEST_TAG | sed 's/v//')
       NEW_VERSION=$(echo $BASE_VERSION | awk -F. '{printf "%d.%d.%d", $1, $2, $3+1}')
       NEW_TAG="uta/$NEW_VERSION"
       echo "New tag: $NEW_TAG"

       # Create new tag and push using PAT for authentication
       git tag $NEW_TAG
       git push origin $NEW_TAG
      