name: Run Script on Server

on:
  push:
    branches:
      - main # Replace with the branch you want to trigger the script

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.DEPLOY_KEY }}

    - name: Execute Script on Server
      run: |
        ssh -o StrictHostKeyChecking=no ubuntu@57.128.216.192 << 'EOF'
          # Navigate to the script's directory if necessary
          sh /apps/dev-env/create-file.sh


          # Optional: Check for errors or success
          echo "Script execution completed!"
        EOF
