name: Releases

on:
  push:
    branches:
      - main

jobs:
  changelog:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Git user
        run: |
          git config --global user.name "divyesh"
          git config --global user.email "divyeshl@zignuts.com"

      - name: Conventional Changelog Action
        id: changelog
        uses: TriPSs/conventional-changelog-action@v3.7.1
        with:
          github-token: ${{ secrets.GH_TOKEN }}  # Ensure the token name is correct and added to your secrets

      - name: Commit Changelog and Tag
        run: |
          git add CHANGELOG.md
          git commit -m "chore(release): v${{ steps.changelog.outputs.tag }}"
          git tag -a "v${{ steps.changelog.outputs.tag }}" -m "v${{ steps.changelog.outputs.tag }}"
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}

      - name: Push changes and tags
        run: |
          git push origin main --follow-tags
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}

      - name: Create release
        uses: actions/create-release@v1
        if: ${{ steps.changelog.outputs.skipped == 'false' }}
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        with:
          tag_name: ${{ steps.changelog.outputs.tag }}
          release_name: ${{ steps.changelog.outputs.tag }}
          body: ${{ steps.changelog.outputs.clean_changelog }}
