name: UAT Server Pipeline

on:
  workflow_dispatch:
    inputs:
      release_notes:
        description: 'Enter the release notes (e.g., Added feature X and fixed bug Y)'
        required: true
      version:
        description: 'Enter the version number (e.g., 1.0.1)'
        required: true
        default: '0.0.1'

jobs:
  build_and_push:
    runs-on: ubuntu-22.04
    permissions:
      contents: write

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0 # Ensure all tags are fetched

    # Step to create a new tag based on the existing tag
    - name: Create new tag from existing tag
      id: bump
      run: |
        # Get the existing version input
        EXISTING_TAG="${{ github.event.inputs.version }}"
        echo "Existing version tag: $EXISTING_TAG"

        # Create new tag with 'uta/' prefix
        NEW_TAG="uta/$EXISTING_TAG"
        echo "New tag: $NEW_TAG"

        # Get the release notes input
        RELEASE_NOTES="${{ github.event.inputs.release_notes }}"
        echo "Release notes: $RELEASE_NOTES"

        # Create an annotated tag with the release notes
        git tag -a $NEW_TAG -m "$RELEASE_NOTES"
        
        # Push new tag using PAT for authentication
        git push origin $NEW_TAG
      env:
        GITHUB_TOKEN: ${{ secrets.GIT_TOKEN }}
